version: '3'
serivces:
  redis:
    image: redis:4.0-alpine
    ports:
      - "6379:6379"
  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
  postgresdb:
    image: postgres:10-alpine
    ports:
      - "5435:5432"
  app:
    build:
      context: ./app
    depends_on:
      - redis
      - mongodb
      - postgresdb
    environment:
      - REDIS_HOST=redis
      - APP_POSTGRES_HOST=postgresdb
      - APP_MONGO_HOST=mongodb
    ports:
      - "5001:5001"
    volumes:
      - /home/alamin/docker:/data
    links:
      - mongodb
      - postgresdb

